# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
np.version.version

'1.18.4'

#### 3. Create a null vector of size 10

In [8]:
arr=np.zeros(10)
print(arr.astype(int))

[0 0 0 0 0 0 0 0 0 0]


#### 4.  How to find the memory size of any array

In [9]:
arr.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [10]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [11]:
arr=np.zeros(10)
arr[4]=1
print(arr.astype(int))

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49

In [13]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [15]:
#using flipud
np.flipud(arr)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [16]:
#using indexing
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
arr=np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [20]:
arr=np.array([1,2,0,0,4,0])
indices=(arr!=0)
print(arr[indices])

[1 2 4]


#### 11. Create a 3x3 identity matrix

In [21]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [23]:
np.random.rand(3,3,3)

array([[[0.20669372, 0.9679044 , 0.47888727],
        [0.83151927, 0.34934382, 0.19558036],
        [0.19872866, 0.14986502, 0.92020668]],

       [[0.17618588, 0.17419007, 0.68723778],
        [0.0296747 , 0.88630985, 0.69989592],
        [0.52980229, 0.64942224, 0.72432278]],

       [[0.90658936, 0.21234397, 0.27103529],
        [0.83468501, 0.60932857, 0.31102006],
        [0.97562532, 0.14797056, 0.9345518 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
arr=np.random.rand(10,10)
print("Max: ",arr.max())
print("Min: ",arr.min())

Max:  0.9911452070380219
Min:  0.006425299057787437


#### 14. Create a random vector of size 30 and find the mean value

In [28]:
arr=np.random.rand(30)
print("Mean: ",arr.mean())

Mean:  0.5497592388672512


#### 15. Create a 2d array with 1 on the border and 0 inside

In [51]:
arr=np.ones((5,5)).astype(int)
arr[1:-1,1:-1]=0
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array?

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [43]:
np.nan == np.nan

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [74]:
arr=np.zeros((5,5))
x=np.array([1,2,3,4])
index=0
for i in range(arr.shape[0]-1):
    arr[i+1,i]=x[index]
    index+=1
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [90]:
arr=np.zeros((6,7,8))
np.unravel_index(99,(6,7,8))

(1, 5, 3)